# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: cg_common 1.4.0 ruby lib

Gem::Specification.new do |s|
  s.name = "cg_common"
  s.version = "1.4.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Benjamin Thouret", "David Fugere", "Nicolas Buduroi"]
  s.date = "2014-02-07"
  s.description = "Currently include:\n * a feedback link helper to create ticket in cg-project"
  s.email = ["bthouret@codegenome.com", "dfugere@codegenome.com", "nbuduroi@gmail.com"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.files = [
    ".gitignore",
    ".ruby-version",
    ".rvmrc",
    "Gemfile",
    "LICENSE",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/views/layouts/footer/_version.html.erb",
    "cg_common.gemspec",
    "examples/README.md",
    "examples/cg_project.yml",
    "examples/monit/delayed_job.erb",
    "examples/monit/monitrc.erb",
    "examples/monit/mysql.erb",
    "examples/monit/server.erb",
    "examples/monit/sphinx.erb",
    "examples/monit/sshd.erb",
    "examples/rails-env.css",
    "lib/cg_common.rb",
    "lib/cg_common/capistrano.rb",
    "lib/cg_common/capistrano/tasks/cg.rb",
    "lib/cg_common/capistrano/tasks/db.rb",
    "lib/cg_common/capistrano/tasks/delayed_job.rb",
    "lib/cg_common/capistrano/tasks/deploy.rb",
    "lib/cg_common/capistrano/tasks/init.rb",
    "lib/cg_common/capistrano/tasks/monit.rb",
    "lib/cg_common/capistrano/tasks/sphinx.rb",
    "lib/cg_common/capistrano/templates/maintenance.erb",
    "lib/cg_common/cg_project_config.rb",
    "lib/cg_common/development_mail_interceptor.rb",
    "lib/cg_common/helpers.rb",
    "lib/cg_common/railtie.rb",
    "test/helper.rb",
    "test/test_jeweler_test.rb"
  ]
  s.homepage = "https://github.com/codegenome/cg_common"
  s.require_paths = ["lib"]
  s.rubyforge_project = "cg_common"
  s.rubygems_version = "2.1.11"
  s.summary = "A bunch of common code that should be used in every project."
  s.test_files = ["test/helper.rb", "test/test_jeweler_test.rb"]

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<cg_common>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano>, [">= 0"])
      s.add_runtime_dependency(%q<capistrano-ext>, [">= 0"])
      s.add_runtime_dependency(%q<erubis>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
    else
      s.add_dependency(%q<cg_common>, [">= 0"])
      s.add_dependency(%q<capistrano>, [">= 0"])
      s.add_dependency(%q<capistrano-ext>, [">= 0"])
      s.add_dependency(%q<erubis>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
    end
  else
    s.add_dependency(%q<cg_common>, [">= 0"])
    s.add_dependency(%q<capistrano>, [">= 0"])
    s.add_dependency(%q<capistrano-ext>, [">= 0"])
    s.add_dependency(%q<erubis>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
  end
end

