Capistrano::Configuration.instance.load do
  before "deploy:update_code" do
    deploy.web.disable
  end

  after "deploy:create_symlink" do
    deploy.web.enable
  end

  namespace :deploy do
    namespace :web do
      desc <<-DESC
        Makes the application web-accessible again. Removes the \
        maintenance.html page generated by deploy:web:disable, which (if your \
        web servers are configured correctly) will make your application \
        web-accessible again.
      DESC
      task :enable, :roles => :web, :except => { :no_release => true } do
        run "rm -f #{shared_path}/system/maintenance.html"
      end

      desc "Present a maintenance page to visitors."
      task :disable, :roles => :web do
        require 'erubis'

        on_rollback { rm "#{shared_path}/system/maintenance.html" }

        deadline, reason = ENV['UNTIL'], ENV['REASON']
        file_path = './app/views/layouts/maintenance.erb'
        unless File.exists? file_path
          file_path = CgCommon.gem_path 'lib', 'cg_common', 'capistrano', 'templates', 'maintenance.erb'
        end
        maintenance_file = File.read file_path
        maintenance = Erubis::Eruby.new(maintenance_file).result(binding)

        put maintenance, "#{shared_path}/system/maintenance.html", :mode => 0644
      end

    end
  end
end
